import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner/Banner'
import Solution from '../components/solution/Solution'
import Steps from '../components/steps/Steps'
import Section from '../components/templates/Section/Section'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ACN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner/>
        <Solution/>
        <Steps/>
        <Section/>
      </main>

    </div>
  )
}
